#!/usr/bin/env sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# The Tests
# =========

# Non-Ascii Filenames
# -------------------

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if test "$(git diff-index --cached --name-only --diff-filter=A -z "$against" |
  # Note that the use of brackets around a tr range is ok here, (it's
  # even required, for portability to Solaris 10's /usr/bin/tr), since
  # the square bracket bytes happen to fall in the designated range.
    LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
then
  cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
  exit 1
fi

# Consistent Plaintext
# --------------------

# Consistent control code usage in plaintext helps keep commit noise low.
# Use the rules in the `.editorconfig` to check whitespace, newlines, and so on.
eclinterr=0
for f in $(git diff-index --cached --name-only --diff-filter=AM "$against"); do
  eclint "$f" || eclinterr=1
done
if [ "$eclinterr" = 1 ]; then
  cat <<\EOF
Error: Attempt to commit code that does not abide by the editorconfig rules.

This repository has a style guide, and I appreciate it being used.

To auto-fix, run

  eclint -fix
EOF
  exit 1
fi

# Git Whitespace Checking
# -----------------------

# If there are whitespace errors, print the offending file names and fail.
# I can probably skip this, since I have the eclint.
#exec git diff-index --check --cached $against --
