###### Explore ######

# List available commands
[group: 'explore']
default:
  @just --list --unsorted

###### Build ######

# Default build: the library and executable.
[group: 'build']
build: build-lib build-exe

# Build the library as an object file (I'm assuming there's just one)
[group: 'build']
build-lib:
  clang -I vendor -std=c23 -fdefer-ts -c lib.c

# Build the executable (I'm assuming there's just one)
[group: 'build']
build-exe: build-lib
  clang -I vendor -std=c23 -fdefer-ts main.c lib.o -o main

###### Document ######

# Build documentation
# (TODO api vs developer docs, also TODO 3rd-party lib documentation)
[group: 'documentation']
docs:
  doxygen

###### Test ######

###### Execute ######

# Run the executable (I'm assuming there's just one)
[group: 'execute']
run: build-exe
  ./main

###### Distribute ######
