srcdir := "src"
appdir := "app"
builddir := ".build"

###### Explore ######

# List available commands
[group: 'explore']
default:
  @just --list --unsorted

###### Build ######

# Default build: the library and executable.
[group: 'build']
build: build-lib build-exe

# Build the library as an object file (I'm assuming there's just one)
[group: 'build']
build-lib:
  clang @compile_flags.txt -c {{srcdir}}/lib.c -o {{builddir}}/lib.o

# Build the executable (I'm assuming there's just one)
[group: 'build']
build-exe: build-lib
  clang @compile_flags.txt {{appdir}}/main.c {{builddir}}/lib.o -o {{builddir}}/main

###### Document ######

# Build documentation
# (TODO api vs developer docs, also TODO 3rd-party lib documentation)
[group: 'documentation']
docs:
  ./scripts/check_undocumented_files.bash
  doxygen

###### Test ######

###### Execute ######

# Run the executable (I'm assuming there's just one)
[group: 'execute']
run: build-exe
  ./main

###### Distribute ######
